🗃️  #147 FEAT : Models와 Migrations 생성
E-GaeMuYac/BE pull request #148
Opened 2023-01-21 16:42 UTC by soogineer

🗃️  #147 FEAT : Models와 Migrations 생성

2023-01-21 19:45 UTC, youngjae0411 requested changes

2023-01-21 19:45 UTC, youngjae0411 commented on src/migrations/20230112072646-create-reivews.js
> +            allowNull: true,
null값 false가 더 적절할 것 같습니다

2023-01-21 19:45 UTC, youngjae0411 commented on src/migrations/20230112072646-create-reivews.js
> +            type: Sequelize.STRING,
그냥 STRING이면 255자인가 제한이 되기때문에 (1000) 이런 식으로 글자수를 프론트와 이야기해서 몇자 제한으로 둘 지 정하고 그에 맞는 수를 넣으면 좋을 거 같습니다.

2023-01-21 19:45 UTC, youngjae0411 commented on src/models/reviews.js
> +        type: DataTypes.STRING,
동일하게 수정 부탁드립니다

2023-01-21 23:42 UTC, soogineer commented on src/migrations/20230112072646-create-reivews.js
> +            allowNull: true,
confirmed

2023-01-21 23:43 UTC, soogineer commented on src/migrations/20230112072646-create-reivews.js
> +            type: Sequelize.STRING,
Ah thanks!

2023-01-21 23:43 UTC, soogineer commented on src/models/reviews.js
> +        type: DataTypes.STRING,
yup!

2023-01-22 11:42 UTC, kimmand0o0 requested changes

2023-01-22 11:42 UTC, kimmand0o0 commented on src/migrations/20230112072646-create-reivews.js
> +            type: Sequelize.STRING(1000),
이미지 몇개까지 받을 지 정하셨나요? 경우에 따라서 json 형태로 받아야 할 수도 있습니다.

2023-01-22 11:42 UTC, kimmand0o0 commented on src/models/medicines.js
> +        foreignKey: 'reviewId',
폴인키 다시 확인 해보셔야 할 것 같습니다.

2023-01-22 11:42 UTC, kimmand0o0 commented on src/models/medicines.js
> +        foreignKey: 'reviewId',
요부분때문에 에러 나는거라 확인 다시 해보세용!!

2023-01-22 11:42 UTC, kimmand0o0 commented on src/models/reviews.js
> +        type: DataTypes.STRING(1000),
위와 동일하게 수정 부탁드립니다.

2023-01-22 11:42 UTC, kimmand0o0 commented on src/models/users.js
> +        foreignKey: 'reviewId',
이부분도 에러가 날겁니다.

2023-01-22 13:34 UTC, soogineer commented on src/migrations/20230112072646-create-reivews.js
> +            type: Sequelize.STRING(1000),
프론트분께 메세지 남겼는데 부재중이시라 임의적으로 정해놨습니다. 수정 될 가능성도 있습니다.

2023-01-22 13:35 UTC, soogineer commented on src/models/medicines.js
> +        foreignKey: 'reviewId',
네 감사합니다.

2023-01-22 13:36 UTC, soogineer commented on src/models/medicines.js
> +        foreignKey: 'reviewId',
confirmed

2023-01-22 13:36 UTC, soogineer commented on src/models/reviews.js
> +        type: DataTypes.STRING(1000),
resolved

2023-01-22 13:37 UTC, soogineer commented on src/models/users.js
> +        foreignKey: 'reviewId',
resolved

2023-01-22 13:59 UTC, youngjae0411 approved these changes

2023-01-22 14:19 UTC, merged