🐛 #147 FIX : 실수코드 정리
E-GaeMuYac/BE pull request #154
Opened 2023-01-22 14:46 UTC by soogineer

- merge 후 conflict 해결중 실수 코드 정리하였습니다. 

- 리뷰 기능 구현중이라 이 부분은 신경 안쓰셔도 될 것 같습니다.

2023-01-22 15:18 UTC, kimmand0o0 requested changes

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +const { Users } = require('../../models');
하나로 합쳐주시면 더 보기 좋을 것 같습니다!

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +      return createReview.dataValues.reviewId;
리턴값이 필요한 지 확인 부탁드립니다!

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +const { Products } = require('../../models');
해당 모델이 있는 지 확인 부탁드립니다!

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +    return Products.findOne({
모델명 확인 부탁드립니다

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +        attributes: ['nickname'],
Medicine이 user를 참조하는 지 확인 부탁드립니다.

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +  createReview = async (medicineId, userId, review) => {
해당 매서드가 두개입니다!

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +const ProductRepository = require('../repositories/products.repository');
두가지 레포를 사용하는 것은 레이어드 아키텍쳐의 장점을 해치는 부분이라 하나의 레포만 사용하는 것이 좋을 것 같습니다!

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +  productRepository = new ProductRepository();
위와 같습니다 :)

2023-01-22 15:18 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneMedicine(createReviews);
코드 확인이 필요 할 것 같습니다.

2023-01-22 16:47 UTC, youngjae0411 requested changes

2023-01-22 16:47 UTC, youngjae0411 commented on src/architecture/controllers/reviews.controller.js
> +      if (!medicineId || !userId || !review) {
useId가 없으면 10번째 줄에서 에러가 나서 13번째 줄에 userId는 의미가 없을 거 같습니다.

2023-01-23 02:40 UTC, soogineer commented on src/architecture/repositories/reviews.repository.js
> +const { Users } = require('../../models');
앗 현재 코드 정리 전이라 구현하고 있는 중이라고 말씀 드렸던 건데, 그래도 확인해주셔서 감사합니다 :)

2023-01-23 02:40 UTC, soogineer commented on src/architecture/repositories/reviews.repository.js
> +const { Users } = require('../../models');
참고하겠습니다

2023-01-23 08:44 UTC, closed without merging