✨  #159 FEAT : 리뷰 CRUD 기능 구현 완료
E-GaeMuYac/BE pull request #171
Opened 2023-01-25 15:58 UTC by soogineer

#159 FEAT : 리뷰 CRUD 기능 구현 완료

- 리뷰 달기
- 리뷰 조회
- 리뷰 수정
- 리뷰 삭제

구현했습니다.

2023-01-25 16:18 UTC, youngjae0411 requested changes

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/controllers/reviews.controller.js
> +        throw new ValidationError('댓글을 작성해주세요.', 412);
댓글보단 리뷰가 맞을 거 같습니다.

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +console.log(delReview)
콘솔 삭제해주세요

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    if (delReview.userId !== userId || userId == undefined) {
userId가 undefined일 경우가 있나요??

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.deleteReview(reviewId);
컨트롤러에서 따로 쓰지않는거 같은데 리턴해주는 이유가 있을까요??

2023-01-25 16:18 UTC, youngjae0411 commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
미들웨어를 넣은 이유가 있을까요??

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/controllers/reviews.controller.js
> +      res.status(200).json({ message: '댓글 등록이 완료되었습니다' });
return 써주는게 좀 더 안전할 것 같습니다.

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/repositories/reviews.repository.js
> +    const review = await Reviews.findOne({
바로 리턴해주세요

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +  findReview = async (medicineId, page, pageSize, loginUserId, reviewId) => {
컨트롤러에서 reviewId 받아오지않고 따로 쓰이지도 않는 거 같습니다.

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +  findReview = async (medicineId, page, pageSize, loginUserId, reviewId) => {
loginUserId는 어디에서 쓰나요?

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    if (changeReview == null || changeReview.length === 0) {
!changeReview로 처리가능하지않나요??

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
컨트롤러에서 쓰지않는데 리턴해주는 이유가 있을까요?

2023-01-25 16:18 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
수정이 됐는데 레포지토리로 find하는 이유가 있을까요?

2023-01-25 16:31 UTC, soogineer commented on src/architecture/controllers/reviews.controller.js
> +        throw new ValidationError('댓글을 작성해주세요.', 412);
confirmed

2023-01-25 16:32 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +console.log(delReview)
넵

2023-01-25 16:33 UTC, kimmand0o0 approved these changes

2023-01-25 16:33 UTC, kimmand0o0 commented on src/architecture/controllers/reviews.controller.js
> +      return res.status(200).json({ message: '댓글 수정완료' });
api 명세서 상으로 댓글 수정 완료가 나가는 게 맞나용?

2023-01-25 16:33 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +    });
18줄부터 28줄까지를 레포에서 안하고 여기서 하는 이유가 있을가요?

2023-01-25 16:33 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +    if (changeReview == null || changeReview.length === 0) {
changeReview는 findOne이라서 원래 length가 없습니당!

2023-01-25 16:33 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +    if (delReview == null || delReview.length === 0) {
delReview는 findOne이라 length가 원래 없습니당

2023-01-25 16:33 UTC, kimmand0o0 commented on src/middlewares/authCheck.middleware.js
> +        } else {
해당 파일은 변경 된 부분이 없는 데 엔터랑 스페이스 때문에 풀이 된 것 같습니다.
git add 파일을 통해 필요한 파일만 업데이트 하면 좋을 것 같습니다.

2023-01-25 16:33 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +        nickname: review['User.nickname'],
유저가 조아요나 싫어요를 눌렀는지와 리뷰의 좋아요 싫어요 수는 어디있을까요?

2023-01-25 16:35 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    if (delReview.userId !== userId || userId == undefined) {
수정했습니다

2023-01-25 16:35 UTC, kimmand0o0 commented on src/app.js
> -
해당 파일은 변경 된 부분이 없는 데 엔터랑 스페이스 때문에 풀이 된 것 같습니다.
git add 파일을 통해 필요한 파일만 업데이트 하면 좋을 것 같습니다.

2023-01-25 16:36 UTC, soogineer commented on src/architecture/controllers/reviews.controller.js
> +      res.status(200).json({ message: '댓글 등록이 완료되었습니다' });
resolved

2023-01-25 16:36 UTC, soogineer commented on src/architecture/repositories/reviews.repository.js
> +    const review = await Reviews.findOne({
confirmed

2023-01-25 16:41 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    if (changeReview == null || changeReview.length === 0) {
confirmed and resolved

2023-01-25 16:43 UTC, soogineer commented on src/app.js
> -
confirmed

2023-01-25 16:44 UTC, soogineer commented on src/middlewares/authCheck.middleware.js
> +        } else {
confirmed

2023-01-25 16:44 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    if (changeReview == null || changeReview.length === 0) {
resolved

2023-01-25 17:07 UTC, soogineer commented on src/architecture/controllers/reviews.controller.js
> +      return res.status(200).json({ message: '댓글 수정완료' });
원래 값을 보내주는건데 다시 수정하겠습니다 :)

2023-01-25 17:10 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
resolved

2023-01-25 17:14 UTC, soogineer commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
router.get할때 말씀하시는건가요?

2023-01-25 17:23 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.deleteReview(reviewId);
컨트롤러에서 쓰고 있습니다.

2023-01-25 17:32 UTC, youngjae0411 commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
네네 리뷰를 불러오는데 미들웨어를 거칠 이유가 있나요??

2023-01-25 17:33 UTC, youngjae0411 requested changes

2023-01-25 17:48 UTC, soogineer commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
앗 이 부분은 get할때 유저가 본인이 쓴 글인 것을 writer로 true/false값을 내보내주는 구현을 했을때 local user와 login된 user를 비교하기위해 넣었던 미들웨어였는데, writer 값을 빼고 이 미들웨어도 삭제하지 않은것 같습니다. 알려주셔서 감사합니다!

2023-01-25 17:48 UTC, soogineer commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
수정하였습니다

2023-01-25 18:31 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.deleteReview(reviewId);
저는 async await 코드 뒤에 항상 return으로 통일해주는게 좋다고 생각해서 리턴 해주었습니다

2023-01-25 18:32 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.deleteReview(reviewId);
그렇지만 컨트롤러에서 사용 안하는거 확인하고 수정했습니다

2023-01-25 18:41 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
이 부분에서 리턴을 해주지 않으면 reviews.controller.js의 코드
`  const updateReview = await this.reviewService.updateReview(reviewId, review, userId);
      return res.status(200).json(updateReview);
    } catch (error) {
      next(error);
    }`중 `return res.status(200).json(updateReview);`에서 updateReview가 undefined로 나옵니다.

2023-01-25 18:43 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +        nickname: review['User.nickname'],
구현 중입니다. 수정과 테스트 후 다시 commit하겠습니다.

2023-01-26 00:20 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
등록은 값을 따로 안 주는데 수정은 값을 주는 것은 이상합니다

2023-01-26 00:23 UTC, youngjae0411 commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
loginuserId를 안 쓰는데 구분할 이유가 없을 것 같습니다.

2023-01-26 01:16 UTC, soogineer commented on src/routes/reviews.route.js
> +router.get('/', authCheckMiddleware, reviewsController.findReview);
디테일하게 말씀드리자면,

리뷰를 불러오는데는 미들웨어를 거칠 필요가 없는데, 로그인한 사람이 어떠한 리뷰를 볼때 그 리뷰에 like/dislike/아무것도 안눌렀는지 봐야하기 때문에 미들웨어를 거쳐야합니다.

2023-01-26 01:41 UTC, closed without merging