✨ #159 FEAT : 리뷰 기능 구현
E-GaeMuYac/BE pull request #172
Opened 2023-01-26 01:47 UTC by soogineer

#159 FEAT : 리뷰 기능 구현 완료
 

- 리뷰 작성
- 리뷰 조회 (+like/dislike/likeCount/dislikeCount)
- 리뷰 수정
- 리뷰 삭제

기능 구현 완료했습니다

2023-01-26 01:56 UTC, kimmand0o0 requested changes

2023-01-26 01:56 UTC, kimmand0o0 commented on src/architecture/controllers/reviews.controller.js
> +const { ValidationError } = require('sequelize');
필요없는 선언인 것 같습니다.

2023-01-26 01:56 UTC, kimmand0o0 commented on src/architecture/controllers/reviews.controller.js
> +      let { reviewId } = req.params;
let으로 적어준 이유가 따로 없다면 const가 더 좋아보입니다.

2023-01-26 01:56 UTC, kimmand0o0 commented on src/architecture/repositories/reviews.repository.js
> +    return Reviews.findAll(data);
data를 서비스에서 처리하는 이유가 무엇인가용?

2023-01-26 01:56 UTC, kimmand0o0 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
이 방식으로 api명세서 상과 같이 데이터가 나오나요?

2023-01-26 01:56 UTC, kimmand0o0 commented on src/migrations/20230122112545-create-likes.js
> +      },
value 삭제 하신 것으로 아는 데 확인 해주세요!

2023-01-26 01:56 UTC, kimmand0o0 commented on src/routes/reviews.route.js
> +const ReviewController = require('../architecture/controllers/reviews.controller');
5번째 줄과 중복으로 보입니다.

2023-01-26 01:59 UTC, soogineer commented on src/architecture/controllers/reviews.controller.js
> +const { ValidationError } = require('sequelize');
extensions에서 설치된 것들 중 자꾸 쓰지 않는 코드가 생겨나는 현상같습니다, 하지만 한번 더 확인하고 commit 하겠습니다. 감사합니다 :)

2023-01-26 02:00 UTC, soogineer commented on src/architecture/controllers/reviews.controller.js
> +      let { reviewId } = req.params;
resolved!

2023-01-26 02:01 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
api 명세서 수정하였습니다.

2023-01-26 02:15 UTC, soogineer commented on src/migrations/20230122112545-create-likes.js
> +      },
confirmed - 삭제한 것으로 확인되는데, 수정 전 파일이 commit된 것 같습니다.

2023-01-26 02:18 UTC, soogineer commented on src/routes/reviews.route.js
> +const ReviewController = require('../architecture/controllers/reviews.controller');
confirmed

2023-01-26 04:30 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
수정하고  굳이 돌려줄 필요가 없어보입니다.

2023-01-26 04:38 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +          dislikeValue = true;
value를 주는 이유를 모르겠습니다.

2023-01-26 04:43 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +
좋아요 등록 api가 없는 상태에서 이 코드가 제대로 동작하는지 알 수 있나요??

2023-01-26 09:45 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +
네, 현재 목데이터 넣어서 확인하고 코드가 작동하는것으로 확인하고 있습니다.

2023-01-26 11:25 UTC, youngjae0411 commented on src/architecture/services/reviews.service.js
> +
개인적인 생각으로는 어차피 구현해야될거라면 좋아요 등록부터 구현이 다 되면 리뷰에 좋아요 조회를 추가하는 것이 더 좋아보입니다

2023-01-26 11:44 UTC, youngjae0411 approved these changes

2023-01-26 12:11 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
api명세서와 동일하게 데이터 나오도록 수정하였습니다 :)

2023-01-26 12:12 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +    return this.reviewRepository.findOneReview(reviewId);
confirmed

2023-01-26 12:13 UTC, soogineer commented on src/architecture/services/reviews.service.js
> +          dislikeValue = true;
프론트쪽에서 `{ like: true, unlike:false,  likeCount:2, unlikeCount:1}` 로 요청하셔서 그렇게 구현하였습니다.

2023-01-27 06:48 UTC, kimmand0o0 approved these changes

2023-01-27 06:48 UTC, merged