✨ FEAT : 구글 소셜 로그인 구현 #35
E-GaeMuYac/BE pull request #49
Opened 2023-01-10 20:02 UTC by soogineer

passport 및 jwt 사용하여 구글 소셜 로그인 기능 구현

1. 구글 개인 정보 동의를 하지 않았을 경우, 닉네임을 받아올 수 없어서 이메일의 @ 앞 아이디를 닉네임으로 대체 해야만 했다. 
2. passport 사용을 처음 해봐서 메소드를 사용하는 데에 익숙치 않았다. 
3. access token과 refresh token을 발급 받고, refresh token을 repository단을 통해 디비에 저장하지 않고, GoogleStrategy에 저장하는 방법이 있었는데, 디비에 과연 어떻게 저장할것인가 고민이 많았는데,  GoogleStrategy단에서의 로그인 플로우를 잘 파악해보고 해결할 수 있었다.

2023-01-10 20:20 UTC, kimmand0o0 requested changes

2023-01-10 20:20 UTC, kimmand0o0 commented on src/app.js
> +const { ApplicationCostProfiler } = require('aws-sdk');
이부분은 어디서 쓰이나요?

2023-01-10 20:20 UTC, kimmand0o0 commented on src/architecture/controllers/login.controller.js
> +    Google = passport.authenticate('google', { scope: ['email'] });
login 매서드 안쪽에 있는 것으로 보입니다. 위치를 다시 확인해주세요

2023-01-10 20:20 UTC, kimmand0o0 commented on src/architecture/controllers/login.controller.js
> +    GoogleCallback = passport.authenticate('google', {
login 매서드 안쪽에 있는 것으로 보입니다. 위치를 다시 확인해주세요

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/GoogleStrategy.js
> +require('../util/token');
4번 줄과 중복으로 보입니다. 삭제해주세요 :)

2023-01-10 20:20 UTC, kimmand0o0 commented on src/architecture/controllers/login.controller.js
> +      failureRedirect: 'http://localhost:3000/api/users/login/google/callback', // GoogleStrategy에서 실패하면 이 주소로 이동
http://localhost:3000/api/users/login/google/callback
해당 url을 아래로 바꿔도 좋을 것 같습니다.
/api/users/login/google/callback

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/GoogleStrategy.js
> +            const accesstoken = await createAccessToken(exUser.userId);
새로 DB에 저장한 user는 newUser로 보입니다.
exUser.userId가 아니라 newUser.userId가 되는 것이 맞을 것 같습니다!

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
위와 마찬가지로 user정보도 같이 들어가야 하지 않을까 싶습니다.

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken, exUser, true]);
true가 역할이 없다면 정리해도 될 것 같습니다.
아래 53번 줄에는 true가 없어 건의드립니다!

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/GoogleStrategy.js
> +          console.error(error);
콘솔로그는 지워도 좋을 것 같습니다 :D

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/index.js
> +
줄 정리가 되면 좋을 것 같습니다 :)

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/index.js
> +    console.log('user', id)
콘솔 로그는 지워도 좋을 것 같습니다!

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/index.js
> +    done(null, user);
user를 user[2].userId로 저장한 후 12번째줄 매서드에서 DB에서 찾아오는 게 더 효율적일 것 같습니다.

2023-01-10 20:20 UTC, kimmand0o0 commented on src/passport/index.js
> +    if (id) return done(null, id);
id값을 통해 user정보를 DB에서 받아오면 좋을 것 같습니다.

2023-01-10 20:20 UTC, kimmand0o0 commented on src/routes/login.route.js
> +  passport.authenticate(
로그인 컨트롤러 정리 후 매서드 사용하는 방식으로 바꿔주면 좋을 것 같습니다.

2023-01-10 20:20 UTC, kimmand0o0 commented on src/routes/login.route.js
> +router.get('/google', passport.authenticate('google', { scope: ['email'] }));
로그인 컨트롤러 정리 후 매서드 사용하는 방식으로 바꿔주면 좋을 것 같습니다.

2023-01-10 20:44 UTC, soogineer commented on src/passport/GoogleStrategy.js
> +require('../util/token');
solved

2023-01-10 20:44 UTC, soogineer commented on src/architecture/controllers/login.controller.js
> +      failureRedirect: 'http://localhost:3000/api/users/login/google/callback', // GoogleStrategy에서 실패하면 이 주소로 이동
solved

2023-01-10 20:45 UTC, soogineer commented on src/passport/index.js
> +    console.log('user', id)
solved!

2023-01-10 20:52 UTC, soogineer commented on src/passport/index.js
> +    done(null, user);
solved

2023-01-10 20:53 UTC, soogineer commented on src/architecture/controllers/login.controller.js
> +    Google = passport.authenticate('google', { scope: ['email'] });
solved!

2023-01-10 20:53 UTC, soogineer commented on src/architecture/controllers/login.controller.js
> +    GoogleCallback = passport.authenticate('google', {
solved!

2023-01-10 20:53 UTC, soogineer commented on src/passport/index.js
> +    if (id) return done(null, id);
solved!

2023-01-10 20:56 UTC, soogineer commented on src/routes/login.route.js
> +  passport.authenticate(
solved!

2023-01-10 20:57 UTC, soogineer commented on src/routes/login.route.js
> +router.get('/google', passport.authenticate('google', { scope: ['email'] }));
solved!

2023-01-10 21:04 UTC, soogineer commented on src/app.js
> +const { ApplicationCostProfiler } = require('aws-sdk');
우선 제 코드에 해당되는 코드는 아닙니다.  영재님과 상의 후에 수정하도록 하겠습니다.

2023-01-10 21:08 UTC, soogineer commented on src/passport/GoogleStrategy.js
> +          console.error(error);
solved

2023-01-11 02:37 UTC, youngjae0411 requested changes

2023-01-11 02:37 UTC, youngjae0411 commented on package.json
> +    "start": "nodemon src/app.js",
중복되서 없어도 될 것 같습니다

2023-01-11 02:37 UTC, youngjae0411 commented on src/app.js
> +const { ApplicationCostProfiler } = require('aws-sdk');
제 코드엔 따로 없습니다. 안 쓰면 지우시면 될 것 같아요

2023-01-11 02:37 UTC, youngjae0411 commented on src/passport/GoogleStrategy.js
> +          done(error);
next를 안 쓰고 done을 쓰는 이유가 뭔가요??

2023-01-11 02:37 UTC, youngjae0411 commented on package.json
> +    "cookie-session": "^2.0.0",
안 쓰이는 것들은 삭제해주면 좋을 것 같습니다

2023-01-11 02:37 UTC, youngjae0411 commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
왜 passport 폴더로 따로 뺴신건가요??

2023-01-11 03:03 UTC, soogineer commented on src/app.js
> +const { ApplicationCostProfiler } = require('aws-sdk');
네, 알겠습니다.

2023-01-11 03:04 UTC, soogineer commented on package.json
> +    "start": "nodemon src/app.js",
solved!

2023-01-11 03:13 UTC, soogineer commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
우선 passport란, 인증절차 로직을 편하게 작업할 수 있게 도와주는 Node.js의 미들웨어입니다. 이 passport를 사용하는 인증 방식으로 Strategy(이 파일에서는 Google Strategy)를 사용했고, 이 외에도 다른 소셜 로그인도 구현해야하기 때문에 각각 Strategy별로 파일을 나누었으면 좋겠다고 생각했고, 그렇기 때문에 따로 passport 폴더로 빼야겠다고 생각했습니다.

2023-01-11 04:35 UTC, youngjae0411 commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
미들웨어인데 미들웨어 폴더가 아닌 passport 폴더에 있나요?

2023-01-11 05:46 UTC, soogineer commented on src/passport/GoogleStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
1. passport가 미들웨어 역할을 하지만, Oauth 자체가 사용자의 비밀번호를 묻지 않고 인증하려는 웹의 계정 정보를 받아 접근권한을 얻는 인증 방식이기 때문에 미들웨어 폴더에 넣지 않고 따로 폴더를 뺐습니다. 
2. 그리고 로컬 로그인을 제외한 소셜로그인(카카오톡, 네이버, 구글)을 passport를 사용해서 구현하기로 하였기 때문에 passport를 사용하는 것을 좀 더 직관적으로 볼 수 있을 것 같다는 판단 하에 passport 폴더를 따로 빼놓았습니다.

2023-01-11 06:21 UTC, youngjae0411 approved these changes

2023-01-11 06:51 UTC, kimmand0o0 approved these changes
고생하셨스빈다!

2023-01-11 07:02 UTC, merged