✨ FEAT :  네이버 소셜 로그인 기능 구현
E-GaeMuYac/BE pull request #59
Opened 2023-01-11 17:53 UTC by soogineer

네이버 소셜 로그인 기능 구현 완료했습니다.

2023-01-11 18:13 UTC, kimmand0o0 requested changes

2023-01-11 18:13 UTC, kimmand0o0 commented on src/routes/login.route.js
> +router.get('/', loginController.ResponseToken);
중복입니다! 구글에서 사용하는 라우터와 같아 삭제해도 될 것 같습니다 :D

2023-01-11 18:13 UTC, kimmand0o0 commented on src/routes/login.route.js
> +//     res.redirect('/');ç
주석들이 필요없어 보입니다!
삭제하면 깔끔할 것 같습니다 :D

2023-01-11 18:16 UTC, kimmand0o0 requested changes

2023-01-11 18:16 UTC, kimmand0o0 commented on src/passport/NaverStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
newUser 혹은 exUser 정보가 같이 done에 담겨 나가야 할 것으로 보입니다.
newUser와 exUser를 하나의 변수로 해서 같이 담아서 넣어주세용!

2023-01-12 01:56 UTC, youngjae0411 commented on src/passport/NaverStrategy.js
> +              email: profile._json.response.email,
어떤 소셜로그인을 이용했는지 구분이 되었으면 좋겠습니다. login이란 칼럼을 새로 만들어 naver,google,kakao,local 이런 식으로 같이 저장되면 좋을 것 같습니다.

2023-01-12 01:56 UTC, youngjae0411 commented on src/passport/NaverStrategy.js
> +              nickname: nickname,
이미지 프로필도 같이 가져와야 할 것 같습니다

2023-01-12 04:25 UTC, soogineer commented on src/routes/login.route.js
> +//     res.redirect('/');ç
confirmed

2023-01-12 04:25 UTC, soogineer commented on src/routes/login.route.js
> +router.get('/', loginController.ResponseToken);
confirmed

2023-01-12 05:44 UTC, soogineer commented on src/passport/NaverStrategy.js
> +              nickname: nickname,
confirmed

2023-01-12 07:12 UTC, soogineer commented on src/passport/NaverStrategy.js
> +              email: profile._json.response.email,
confirmed

2023-01-12 07:13 UTC, youngjae0411 commented on src/passport/NaverStrategy.js
> +              nickname: nickname,
nickname : nickname 보단 변수명이 같으니 refreshtoken처럼 nickname 한번만 써도 될 것 같습니다.

2023-01-12 07:14 UTC, soogineer commented on src/passport/NaverStrategy.js
> +              nickname: nickname,
확인하고 수정했습니다!

2023-01-12 07:15 UTC, youngjae0411 approved these changes
GO

2023-01-12 07:16 UTC, kimmand0o0 commented on src/passport/NaverStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
아하 그러면 newUser만 담아서 나가면 될 것 같습니다!

2023-01-12 07:17 UTC, soogineer commented on src/passport/NaverStrategy.js
> +            done(null, [accesstoken, refreshtoken]); // 회원가입하고 로그인 인증 완료
확인했습니다!

2023-01-12 07:51 UTC, youngjae0411 requested changes

2023-01-12 07:51 UTC, youngjae0411 commented on src/passport/NaverStrategy.js
> +          if (NaverExUser) {
소셜로 회원가입을 하지않고 로컬로 회원가입 한 후 동일한 이메일로 소셜로그인을 시도하면 로그인이 됩니다. 어떤 소셜로그인을 이용했는지 구분 짓고 확인해주면 좋을 것 같습니다.

2023-01-12 12:43 UTC, soogineer commented on src/passport/NaverStrategy.js
> +          if (NaverExUser) {
confirmed

2023-01-12 12:48 UTC, kimmand0o0 requested changes

2023-01-12 12:48 UTC, kimmand0o0 commented on src/passport/NaverStrategy.js
> +              email: profile._json.response.email,
DB Users 테이블에 칼럼과 구분점이 만들어지지 않은 것 같습니다!
다시 확인 부탁드려용!

2023-01-12 12:54 UTC, youngjae0411 commented on src/passport/NaverStrategy.js
> +              email: profile._json.response.email,
이렇게 하면 회원가입만 가능하고 로그인이 불가할 것 같습니다.  login이란 칼럼을 하나 더 만든 뒤 naver,google,kakao,local 이런 식으로 회원가입 시 저장하고 로컬 로그인이면 OP.and을 통해서 email과 login이 local인걸 찾고, 네이버면 똑같이 OP.and를 통해서 email과 login : naver 이런 식으로 짜면 될 것 같습니다.

2023-01-13 21:21 UTC, closed without merging

2023-01-14 19:48 UTC, soogineer commented on src/passport/NaverStrategy.js
> +              email: profile._json.response.email,
confirmed